# Site

# Content configuration version
version: 2

# Personal info
name: Ekarat Rattagan, Ph.D.
title: Lecturer at Graduate school of Applied Statistics, NIDA, Bangkok, Thailand
email: ekarat@as.nida.ac.th
website: https://as.nida.ac.th/#

# Dark Mode (true/false/never)
darkmode: false

